from curses.ascii import isalpha
# given words of string
words = "gsv yvhg kiltiznh ziv dirggvm hl gszg xlnkfgrmt nzxsrmvh xzm kviulin gsvn jfrxpob. zohl, gsv yvhg kiltiznh ziv dirggvm hl gszg sfnzm yvrmth xzm fmwvihgzmw gsvn xovziob. z tllw vhhzbrhg zmw z tllw kiltiznnvi szev z olg rm xlnnlm."
# split words of string into the list of words
wordList = words.split(' ')
# add new word generated by applying all the conditions
newWordList = []
# Iterate list of words
for word in wordList:
    # get new generated word
    updatedWord = ""
    # Iterate each character
    for ch in word:
        # if current char is alphabetic then
        # apply condition
        if isalpha(ch):
            # get ascii integer value of char using ord()
            # substract this integer value from 219
            # get absolute value of updated integer value using abs()
            # get char of updated integer using chr()
            # append into the updatedWord
            updatedWord = updatedWord + chr(abs(219-ord(ch)))
        # else append as it is
        else:
            updatedWord = updatedWord + ch
    # append updatedWord into the newWord list
    newWordList.append(updatedWord)

# join the list to the string
ans = (' ').join(newWordList)
print(ans)
